substitutions:
  wifi_ssid: ssid
  wifi_password: password
  wifi_ap_passwort: password
  wifi_domain: ".local"
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  domain: ${wifi_domain}
  ap:
    ssid: ${device_name}
    password: ${wifi_ap_passwort}
captive_portal:
