substitutions:
  # without_pin: set to "true" if no PIN is entered in powermeter. 
  ## Consumption and production are more accurate if the PIN is entered and needs to be calculated. 
  ## This also removes the unavailable power sensor in case no pin is provided.
  without_pin: "false"
  consumption_throttle: 60s
  production_throttle: 60s
  power_throttle: 15s # uses throttle_average to have a more accurate value
  sml_rx: GPIO20
  sml_tx: GPIO21
  sml_baud_rate: "9600"
esphome:
  project:
    name: "dergeberl.iskra-mt631"
    version: "v0.0.0"
uart:
  id: uart_bus
  tx_pin: ${sml_tx}
  rx_pin: ${sml_rx}
  baud_rate: ${sml_baud_rate}
sml:
  id: sml_bus
  uart_id: uart_bus
## iskra mt631 (in my case from netzebw)
## without PIN only the following OBIS codes are availible:
### 1-0:1.8.0 total consumption (only in kwh steps)
### 1-0:2.8.0 total feed (only in kwh steps)
##
## with PIN the following OBIS codes are availible:
### 1-0:1.8.0 total consumption (/10000 to get kwh)
### 1-0:2.8.0 total feed  (/10000 to get kwh)
### 1-0:16.7.0 current power
##
## always availible
### 1-0:96.50.1 manufacturer
### 1-0:96.1.0 server id
sensor:
  - platform: sml
    name: "${friendly_name} consumption"
    sml_id: sml_bus
    obis_code: "1-0:1.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing
    filters:
      - throttle: ${consumption_throttle}
      - lambda: |-
          if ("${without_pin}" == "true") return x;
          return x/10000;
  - platform: sml
    name: "${friendly_name} production"
    sml_id: sml_bus
    obis_code: "1-0:2.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing
    filters:
      - throttle: ${production_throttle}
      - lambda: |-
          if ("${without_pin}" == "true") return x;
          return x/10000;
  - platform: sml
    name: "${friendly_name} power"
    internal: ${without_pin}
    sml_id: sml_bus
    obis_code: "1-0:16.7.0"
    unit_of_measurement: W
    accuracy_decimals: 0
    device_class: power
    state_class: measurement
    filters:
      - throttle_average: ${power_throttle}
text_sensor:
  - platform: sml
    name: "${friendly_name} manufacturer"
    entity_category: diagnostic
    disabled_by_default: true
    sml_id: sml_bus
    obis_code: "1-0:96.50.1"
    format: text
    icon: mdi:information
  - platform: sml
    name: "${friendly_name} Server ID"
    entity_category: diagnostic
    disabled_by_default: true
    sml_id: sml_bus
    obis_code: "1-0:96.1.0"
    format: int
    icon: mdi:identifier
