substitutions:
  device_name: device-name
  friendly_name: "Friendly Name"
  uart_tx_pin: GPIO21
  uart_rx_pin: GPIO20
  sen0395_gpio_pin: GPIO5
  sen0395_detection_segment_start: "0cm"
  sen0395_detection_segment_end: "9m"
  sen0395_delay_after_detect: "0s"
  sen0395_delay_after_disappear: "3s"
  sen0395_led: "false"
  sen0395_sensitivity: "7"
esphome:
  project:
    name: "dergeberl.presence"
    version: "v0.0.0"
external_components:
  - source: github://pr#4203
    components: [ dfrobot_mmwave_radar ]
uart:
  id: uart_sen0395
  tx_pin: ${uart_tx_pin}
  rx_pin: ${uart_rx_pin}
  baud_rate: 115200
dfrobot_mmwave_radar:
binary_sensor:
  - platform: gpio
    name: ${friendly_name} Presence
    id: sen0395_presence
    device_class: motion
    pin:
      number: ${sen0395_gpio_pin}
      mode: INPUT_PULLDOWN
    on_state:
      - script.execute: update_presence_led
switch:
  - platform: template
    name: ${friendly_name} Presence Sensor
    id: sen0395_sensor
    entity_category: config
    restore_state: true
    optimistic: true
    turn_on_action:
      - dfrobot_mmwave_radar.start
    turn_off_action:
      - dfrobot_mmwave_radar.stop
  - platform: template
    name: ${friendly_name} Presence LED
    id: presence_led
    entity_category: config
    restore_state: true
    optimistic: true
    turn_on_action:
      - delay: 1s
      - script.execute: update_presence_led
    turn_off_action:
      - delay: 1s
      - script.execute: update_presence_led
button:
  - platform: template
    name: ${friendly_name} presence sensor factory_reset
    id: sen0395_sensor_factory_reset
    entity_category: diagnostic
    on_press:
      - dfrobot_mmwave_radar.settings:
          factory_reset: true
  - platform: template
    name: ${friendly_name} presence sensor restart
    id: sen0395_sensor_restart
    entity_category: diagnostic
    on_press:
      - dfrobot_mmwave_radar.reset
  - platform: template
    name: ${friendly_name} presence sensor reconfigure
    id: sen0395_sensor_reconfigure
    entity_category: diagnostic
    on_press:
      - dfrobot_mmwave_radar.settings:
          factory_reset: true
          detection_segments:
            - ${sen0395_detection_segment_start}
            - ${sen0395_detection_segment_end}
          output_latency:
            delay_after_detect: ${sen0395_delay_after_detect}
            delay_after_disappear: ${sen0395_delay_after_disappear}
          start_after_power_on: true
          turn_on_led: ${sen0395_led}
          presence_via_uart: false
          sensitivity: ${sen0395_sensitivity}
light:
  - platform: binary
    id: presence_info_led
    internal: true
    output: presence_info_led_output
  - platform: status_led
    id: s_led
    internal: true
    pin: GPIO3
output:
  - id: presence_info_led_output
    platform: gpio
    pin: GPIO4
script:
  - id: update_presence_led
    mode: restart
    then:
      - if:
          condition:
            switch.is_on: presence_led
          then:
            - if:
                condition:
                  binary_sensor.is_on: sen0395_presence
                then:
                  - light.turn_on:
                      id: presence_info_led
                else:
                  - light.turn_off:
                      id: presence_info_led
            - script.stop: update_presence_led
      - light.turn_off:
          id: presence_info_led
