substitutions:
  device_name: example-velux
  friendly_name: "Example"
  wifi_ssid: "ssid"
  wifi_password: "password"

packages:
  remote_package:
    url: https://github.com/dergeberl/esphome-packages
    ref: main
    files: 
      - boards/seeed-xiao-esp32c3.yaml
      - default/main.yaml
      - default/logger.yaml
      - default/wifi.yaml
      - default/diagnostic.yaml
      - default/webserver.yaml
      - default/status.yaml
      - default/time.yaml
      - devices/velux-kli-31x.yaml
    refresh: 1s

api:
# !use encryption!
#  encryption:
#    key: "XXX"

ota:
  password: "CHANGEME"
